version: '3.8'

services:
  mysql:
    image: mysql:8.0.33-alpine
    container_name: mysql_container
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: canchu
    volumes:
      - /var/lib/mysql:/var/lib/mysql  
    networks:
      - canchu_network

  canchu:
    image: canchu_image:latest
    container_name: canchu_container
    volumes:
      - /home/ubuntu/EC2/Canchu/api1.0/public/:/app
    networks:
      - canchu_network

  redis:
    image: redis:6.0.16-alpine
    container_name: redis_container
    networks:
      - canchu_network

  # nginx:
  #   image: nginx:1.18.0-alpine
  #   container_name: nginx_container
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /etc/nginx/sites-available/myapp.conf:/etc/nginx/conf.d  # 替換為您的設定檔路徑
  #     - /etc/ssl/certificate.crt:/etc/nginx/ssl  # 替換為您的 SSL 證書路徑
  #     - /etc/ssl/private/private.key:/etc/ssl/private/private.key  # 替換為 SSL 私鑰的路徑
  #   networks:
  #     - canchu_network  
  #   depends_on:
  #     - canchu

networks:
  canchu_network:   
