version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: onetwothree
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql  
      - ./canchu_database.sql:/docker-entrypoint-initdb.d/canchu_database.sql
    command: ["--init-file", "/docker-entrypoint-initdb.d/canchu_database.sql"] 
    networks:
      - canchu_network

  canchu:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: canchu_container
    # volumes:
    #   - /home/ubuntu/EC2/Canchu/api1.0/public/:/public
    networks:
      - canchu_network

  redis:
    image: redis:6.0.16
    container_name: redis
    restart: always
    networks:
      - canchu_network

  nginx:
    image: nginx:1.18.0
    container_name: nginx
    # restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/sites-available/myapp.conf:/etc/nginx/conf.d/default.conf  # 替換為您的設定檔路徑
      - /etc/ssl/certificate.crt:/etc/ssl/certificate.crt  # 替換為您的 SSL 證書路徑
      - /etc/ssl/private/private.key:/etc/ssl/private/private.key  # 替換為 SSL 私鑰的路徑
    networks:
      - canchu_network  
    depends_on:
      - canchu
volumes:
  mysql_data:

networks:
  canchu_network:   
