name: canchu workflow

on:
  push:
    branches: [master]

jobs:
  test_canchu:
    runs-on: ubuntu-latest
    steps:
    - name: Check code
      uses: actions/checkout@v3
    - name: Build docker compose for test
      run: |
        cd Canchu/api1.0
        echo "${{ secrets.ENV }}" > .env
        echo "${{ secrets.PRIVATE_KEY }}" > private/private.key
        echo "${{ secrets.CERTIFICATE }}" > private/certificate.crt
        docker-compose up -d
    - name: Wait for containers to start
      run: sleep 20
    - name: Run unit test
      run: docker exec canchu_container npm test -- --watch=false

  deploy_canchu:
    needs: test_canchu
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to ec2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd EC2/Canchu/api1.0
          git pull origin master
          if [ ! -d "private" ]; then
            mkdir private
          fi
          echo "${{ secrets.ENV }}" > .env
          echo "${{ secrets.PRIVATE_KEY }}" > private/private.key
          echo "${{ secrets.CERTIFICATE_CRT }}" > private/certificate.crt
          docker-compose down
          docker-compose --build -d
          docker image prune -af